datasets/BEIS-2005-to-2019-local-authority-carbon-dioxide-CO2-emissions/info.json, datasets/BEIS-2005-to-2019-local-authority-carbon-dioxide-CO2-emissions/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/21
1. landing page on info.json corrected to include content page 
2. main.py created in line with spec
=> BEIS-2005-to-2019-local-authority-carbon-dioxide-CO2-emissions

datasets/BEIS-Supplementary-tables-2019-UK-greenhouse-gas-emissions-by-Standard-Industrial-Classification/info.json, datasets/BEIS-Supplementary-tables-2019-UK-greenhouse-gas-emissions-by-Standard-Industrial-Classification/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/23
1. correct landing page included on info.json
2. transform completed
=> BEIS-Supplementary-tables-2019-UK-greenhouse-gas-emissions-by-Standard-Industrial-Classification

datasets/DEFRA-ENV01-Emissions-of-air-pollutants/main.py
https://github.com/GSS-Cogs/family-climate-change/issues/6
Transform done in line with detailed spec
=> DEFRA-ENV01-Emissions-of-air-pollutants

datasets/DEFRA-E8-Efficient-use-of-water/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/39
transform completed
=> DEFRA-E8-Efficient-use-of-water/

datasets/DEFRA-B3-State-of-the-water-environment/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/42
Transform completed
=> DEFRA-B3-State-of-the-water-environment

datasets/BEIS-Sub-national-road-transport-fuel-consumption-in-the-United-Kingdom/info.json, datasets/BEIS-Sub-national-road-transport-fuel-consumption-in-the-United-Kingdom/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/34
Transform done
Spec not available yet
=> BEIS-Sub-national-road-transport-fuel-consumption-in-the-United-Kingdom

datasets/BEIS-2019-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source/info.json
https://github.com/GSS-Cogs/climate-change-govuk/issues/404
https://github.com/GSS-Cogs/climate-change-govuk/issues/406
info.json updated to include uri and value
=> BEIS-2019-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source

datasets/BEIS-2019-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user/info.json, datasets/BEIS-2019-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user/main.py
switching to csvcubed Jenkins pipeline
=> BEIS-2019-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user

datasets/BEIS-Provisional-UK-greenhouse-gas-emissions-national-statistics-2021/info.json, datasets/BEIS-Provisional-UK-greenhouse-gas-emissions-national-statistics-2021/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/407
=> BEIS-Provisional-UK-greenhouse-gas-emissions-national-statistics-2021

datasets/BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user/info.json, datasets/BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/404
=> BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-end-user

datasets/BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source/info.json, datasets/BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/406
=> BEIS-2020-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source

datasets/ONS-Atmospheric-emissions-greenhouse-gases-by-industry-and-gas-1990-2020/main.py
correcting script to use only industry total for 'GHG total'
=> ONS-Atmospheric-emissions-greenhouse-gases-by-industry-and-gas-1990-2020

datasets/BEIS-2005-to-2019-local-authority-carbon-dioxide-CO2-emissions/info.json, datasets/BEIS-2005-to-2019-local-authority-carbon-dioxide-CO2-emissions/main.py
https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/490
A new datacube is being uploaded to PMD - Alpha, with two additional measures created:
1. territorial emissions per capital 
2. territorial emissions per area
=> SPARQL query for per capita CO2 emissions per LA 

datasets/DEFRA-Carbon-Footprint-Summary-Final-Demand-90-19/info.json, datasets/DEFRA-Carbon-Footprint-Summary-Final-Demand-90-19/main.py
1.  Column mapping done
2. Transformation completed successfully
#502
=> DEFRA-Carbon-Footprint-Summary-Final-Demand-90-19

datasets/DEFRA-Carbon-Footprint-Summary-Product-90-19/info.json, datasets/DEFRA-Carbon-Footprint-Summary-Product-90-19/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/503.
Transformation made for
1. Create main.py to new legacy pipeline
2. Info.json to latest v1.1.0
=> DEFRA-Carbon-Footprint-Summary-Product-90-19

datasets/DEFRA-Carbon-Footprint-Summary-Source-Region-90-19/info.json, datasets/DEFRA-Carbon-Footprint-Summary-Source-Region-90-19/main.py
Transformation made as follows
1. Create main.py to new legacy pipeline
2. Create new info.json v1.1.0
=> DEFRA-Carbon-Footprint-Summary-Source-Region-90-19

datasets/BEIS-Energy-Trends-Table-1-2-Extract-2021/info.json, datasets/BEIS-Energy-Trends-Table-1-2-Extract-2021/main.py
Transformation did as follows:
1. main.py
2. info.json
=> BEIS-Energy-Trends-Table-1-2-Extract-2021

datasets/DEFRA-E8-Efficient-use-of-water-20-21/info.json, datasets/DEFRA-E8-Efficient-use-of-water-20-21/main.py
Transformation 
1. main.py to new legacy pipeline
2. transcript info.json
=> DEFRA-E8-Efficient-use-of-water-20-21

datasets/DEFRA-UK-Water-Leakage-20-21/info.json, datasets/DEFRA-UK-Water-Leakage-20-21/main.py
transformation did on period for 
1. main.py
2. info.json
=> DEFRA-UK-Water-Leakage-20-21

datasets/Met-Office-Regional-average-climate-observations-UK-annual-rainfall-2021/info.json, datasets/Met-Office-Regional-average-climate-observations-UK-annual-rainfall-2021/main.py
Transformation as follows
1. main.py
2. info.json
=> Met-Office-Regional-average-climate-observations-UK-annual-rainfall-2021

datasets/Met-Office-Regional-average-climate-observations-UK-annual-mean-temperature-2021/info.json, datasets/Met-Office-Regional-average-climate-observations-UK-annual-mean-temperature-2021/main.py
Transformation to 
1. main.py
2. info.json
=> Met-Office-Regional-average-climate-observations-UK-annual-mean-temperature-2021

datasets/ONS-Atmospheric-emissions-greenhouse-gases-by-industry-and-gas-1990-to-2020-and-provisional-2021/main.py
https://app.zenhub.com/workspaces/cogs-data-60d307ddb4e5d4001aad35e1/issues/gss-cogs/family-climate-change/550
corrected tab name from 'GHG total' to 'Total GHG'
=> ONS-Atmospheric-emissions-greenhouse-gases-by-industry-and-gas-1990-to-2020-and-provisional-2021

datasets/BEIS-Energy-Intensity-Extract-1970-2021/info.json, datasets/BEIS-Energy-Intensity-Extract-1970-2021/main.py
Transformation and script are as follows:
1. main.py
2. info.json
=> BEIS-Energy-Intensity-Extract-1970-2021

datasets/BEIS-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source-2021/info.json, datasets/BEIS-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source-2021/main.py
Transforms to the dataset as follows
1. main.py
2. info.json
=> BEIS-UK-greenhouse-gas-emissions-final-figures-dataset-of-emissions-by-source-2021

datasets/DLUHC-Domestic-Energy-Performance-Certificates-for-existing-dwellings-by-energy-efficiency-rating-2022/info.json, datasets/DLUHC-Domestic-Energy-Performance-Certificates-for-existing-dwellings-by-energy-efficiency-rating-2022/main.py
Transformation to main.py and info.json
=> DLUHC-Domestic-Energy-Performance-Certificates-for-existing-dwellings-by-energy-efficiency-rating-2022

datasets/ONS-Energy-use-fossil-fuels-by-fuel-type-and-industry/info.json, datasets/ONS-Energy-use-fossil-fuels-by-fuel-type-and-industry/main.py
Transformation to 
1. main.py
2. info.json
=> ONS-Energy-use-fossil-fuels-by-fuel-type-and-industry
